### ISSUE TITLE
no doc nor man nor button

### ISSUE THREAD

**Issue by seanearlyaug** [sizzlemctwizzle/UserScripts#1]
I can not find a way to activate this script, no new buttons, nothing, no documentation. 
OK I am new to greasemonkey.

**Comment by sizzlemctwizzle** [comment]
It registers menu items with Greasemonky that are used to trigger it. I really need to update it since it is still a relevant. I met several people in college who really enjoyed the challenge of writing things in Brainfuck, and when I introduced them to this script (that I wrote in high school) they were hooked even more.

**Comment by sizzlemctwizzle** [comment]
https://openuserjs.org/about/Userscript-Beginners-HOWTO
